// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Web instance:": {
        "en": "Web instance",
        "de": "Web Instance",
        "ru": "Web instance",
        "pt": "Instancia do servidor da Web",
        "nl": "Web-instantie",
        "fr": "Instance du serveur Web",
        "it": "Istanza del server Web",
        "es": "Instancia del servidor web"
    },        
    "Web server IP:": {
        "en": "Web server IP",
        "de": "Web Server IP",
        "ru": "IP Веб сервера",
        "pt": "IP do servidor da Web",
        "nl": "Webserver IP",
        "fr": "IP du serveur Web",
        "it": "IP del server Web",
        "es": "IP del servidor web"
    }
};
