/*global systemDictionary:true */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
'use strict';

systemDictionary = {
    "Web instance:": {                                "en": "Web instance",                                     "de": "Web Instance",                                     "ru": "Web instance",                                     "pt": "Instancia do servidor da Web",                     "nl": "Web-instantie",                                    "fr": "Instance du serveur Web",                          "it": "Istanza del server Web",                           "es": "Instancia del servidor web",                       "pl": "Instancja internetowa",                            "zh-cn": "网络实例"},
    "Web server IP:": {                               "en": "Web server IP",                                    "de": "Web Server IP",                                    "ru": "IP Веб сервера",                                   "pt": "IP do servidor da Web",                            "nl": "Webserver IP",                                     "fr": "IP du serveur Web",                                "it": "IP del server Web",                                "es": "IP del servidor web",                              "pl": "IP serwera WWW",                                   "zh-cn": "网络服务器 IP"},
};